import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { doctor, init, migrate } from './config.mjs';

const roots = [];
const script = fileURLToPath(new URL('./config.mjs', import.meta.url));
async function repo() { const value = await mkdtemp(path.join(os.tmpdir(), 'ios-release-config-')); roots.push(value); execFileSync('git', ['init', '--quiet', value]); return value; }
function app(extra = {}) { return { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' }, releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' }, ...extra }; }
test.after(async () => { for (const root of roots) execFileSync('rm', ['-rf', root]); });

test('init creates a visible portable config and ignored local binding idempotently', async () => { const root = await repo(); const first = await init(root); assert.deepEqual(first.created, { '.ios-release/.gitignore': true, '.ios-release/config.json': true, '.ios-release/local.json': true }); assert.equal(first.portableVisible, true); assert.equal(first.localIgnored, true); const second = await init(root); assert.deepEqual(second.created, { '.ios-release/.gitignore': false, '.ios-release/config.json': false, '.ios-release/local.json': false }); assert.equal(await readFile(path.join(root, '.ios-release/.gitignore'), 'utf8'), '*\n!.gitignore\n!config.json\n'); assert.equal((await stat(path.join(root, '.ios-release/local.json'))).mode & 0o777, 0o600); const visible = execFileSync('git', ['-C', root, 'status', '--short', '--untracked-files=all'], { encoding: 'utf8' }); assert.match(visible, /\.ios-release\/\.gitignore/); assert.match(visible, /\.ios-release\/config\.json/); assert.doesNotMatch(visible, /local\.json/); });
test('doctor accepts a complete portable and local split', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, defaultApp: 'app', apps: { app: app() } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'ready'); assert.deepEqual(result.errors, []); });
test('doctor rejects unsafe and transient configuration', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app({ releaseNotes: { archiveDirectory: '../build', sourceLocale: 'en-US', locales: ['zh-Hant'], promotionalText: 'preserve' }, buildId: '42' }) } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /path escapes|transient|sourceLocale/); });
test('migration plan is read-only and apply preserves a V1 backup', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await writeFile(path.join(root, '.git/info/exclude'), '/.ios-release/\nother\n'); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify({ schemaVersion: 1, defaultApp: 'app', apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', ascProfile: 'team', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); const plan = await migrate(root, 'plan'); assert.equal(plan.state, 'planned'); assert.equal(plan.portable.apps.app.releaseNotes.archiveDirectory, 'release-notes'); assert.equal((await stat(path.join(root, '.ios-release/context.json'))).isFile(), true); const applied = await migrate(root, 'apply'); assert.equal(applied.state, 'migrated'); const portable = JSON.parse(await readFile(path.join(root, '.ios-release/config.json'), 'utf8')); const local = JSON.parse(await readFile(path.join(root, '.ios-release/local.json'), 'utf8')); assert.equal(portable.apps.app.ascProfile, undefined); assert.equal(local.apps.app.ascProfile, 'team'); assert.equal((await stat(path.join(root, '.ios-release/context.v1.backup.json'))).isFile(), true); assert.doesNotMatch(await readFile(path.join(root, '.git/info/exclude'), 'utf8'), /\/\.ios-release\//); const rerun = await migrate(root, 'apply'); assert.equal(rerun.state, 'migrated'); assert.equal(rerun.sourcePresent, false); });
test('migration stops for an archive-location choice', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await mkdir(path.join(root, 'release-notes/ios/app'), { recursive: true }); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify({ schemaVersion: 1, apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); const result = await migrate(root, 'plan'); assert.equal(result.state, 'incomplete'); assert.deepEqual(result.candidates.app, ['release-notes/ios/app', 'release-notes']); });

test('CLI emits structured JSON', async () => { const root = await repo(); const result = spawnSync(process.execPath, [script, 'doctor', '--repo', root], { encoding: 'utf8' }); assert.equal(result.status, 1); assert.equal(JSON.parse(result.stdout).state, 'conflict'); });
