import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, stat, symlink, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { doctor, init, migrate } from './config.mjs';

const roots = [];
const script = fileURLToPath(new URL('./config.mjs', import.meta.url));
async function repo() { const value = await mkdtemp(path.join(os.tmpdir(), 'ios-release-config-')); roots.push(value); execFileSync('git', ['init', '--quiet', value]); return value; }
function app(extra = {}) { return { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' }, releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' }, ...extra }; }
test.after(async () => { for (const root of roots) execFileSync('rm', ['-rf', root]); });

test('init creates a visible portable config and ignored local binding idempotently', async () => { const root = await repo(); const first = await init(root); assert.deepEqual(first.created, { '.ios-release/.gitignore': true, '.ios-release/config.json': true, '.ios-release/local.json': true }); assert.equal(first.portableVisible, true); assert.equal(first.localIgnored, true); const second = await init(root); assert.deepEqual(second.created, { '.ios-release/.gitignore': false, '.ios-release/config.json': false, '.ios-release/local.json': false }); assert.equal(await readFile(path.join(root, '.ios-release/.gitignore'), 'utf8'), '*\n!.gitignore\n!config.json\n'); assert.equal((await stat(path.join(root, '.ios-release/local.json'))).mode & 0o777, 0o600); const visible = execFileSync('git', ['-C', root, 'status', '--short', '--untracked-files=all'], { encoding: 'utf8' }); assert.match(visible, /\.ios-release\/\.gitignore/); assert.match(visible, /\.ios-release\/config\.json/); assert.doesNotMatch(visible, /local\.json/); });
test('init rejects symlinked configuration directories and files before writes or chmod', async () => { const root = await repo(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-config-outside-')); roots.push(outside); await symlink(outside, path.join(root, '.ios-release')); await assert.rejects(init(root), /symlinks are forbidden/); await assert.rejects(readFile(path.join(outside, 'config.json')), /ENOENT/); await unlink(path.join(root, '.ios-release')); await init(root); const externalLocal = path.join(outside, 'local.json'); await writeFile(externalLocal, '{}', { mode: 0o644 }); await unlink(path.join(root, '.ios-release/local.json')); await symlink(externalLocal, path.join(root, '.ios-release/local.json')); await assert.rejects(init(root), /local\.json: symlinks are forbidden/); assert.equal((await stat(externalLocal)).mode & 0o777, 0o644); });
test('doctor accepts a complete portable and local split', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, defaultApp: 'app', apps: { app: app() } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'ready'); assert.deepEqual(result.errors, []); });
test('doctor requires a local profile for every portable app', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app() } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: {} })); const result = await doctor(root); assert.equal(result.state, 'incomplete'); assert.deepEqual(result.missing, ['.ios-release/local.json.apps.app.ascProfile']); });
test('doctor rejects archive symlinks that leave the repository', async () => { const root = await repo(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-outside-')); roots.push(outside); await init(root); await symlink(outside, path.join(root, 'release-notes')); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app() } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /symlink|outside|escapes/); });
test('doctor accepts language-only App Store locales', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app({ releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'ja', locales: ['ja'], promotionalText: 'preserve' } }) } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); assert.equal((await doctor(root)).state, 'ready'); });
test('doctor rejects malformed TestFlight group IDs', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app({ testflight: { internalGroups: [{ id: `12345678${'-'.repeat(27)}`, name: 'Internal' }] } }) } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /invalid group ID/); });
test('doctor rejects duplicate TestFlight group IDs regardless of hex casing', async () => { const root = await repo(); await init(root); const id = 'ABCDEF12-1234-1234-1234-123456789ABC'; await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app({ testflight: { internalGroups: [{ id, name: 'Internal' }], externalGroups: [{ id: id.toLocaleLowerCase('en-US'), name: 'External' }] } }) } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /duplicate group ID/); });
test('doctor rejects archive collisions between apps', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, defaultApp: 'first', apps: { first: app(), second: app({ bundleId: 'com.example.second', appId: '987654321' }) } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { first: { ascProfile: 'team' }, second: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /archiveDirectory.*collides/); });
test('doctor rejects archive collisions that differ only by path casing', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, defaultApp: 'first', apps: { first: app({ releaseNotes: { archiveDirectory: 'release-notes/App', sourceLocale: 'en-US', locales: ['en-US'], promotionalText: 'preserve' } }), second: app({ bundleId: 'com.example.second', appId: '987654321', releaseNotes: { archiveDirectory: 'release-notes/app', sourceLocale: 'en-US', locales: ['en-US'], promotionalText: 'preserve' } }) } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { first: { ascProfile: 'team' }, second: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /archiveDirectory.*collides/); });
test('doctor validates parsed falsy JSON values instead of reporting ready', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), 'null\n'); await writeFile(path.join(root, '.ios-release/local.json'), 'null\n'); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.equal(result.errors.filter((error) => error === '$: expected an object').length, 2); });
test('doctor rejects an existing archive path that is not a directory', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, 'release-notes'), 'not a directory\n'); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app() } })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { ascProfile: 'team' } } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /archiveDirectory.*directory/); });
test('doctor rejects unsafe and transient configuration', async () => { const root = await repo(); await init(root); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: app({ releaseNotes: { archiveDirectory: '../build', sourceLocale: 'en-US', locales: ['zh-Hant'], promotionalText: 'preserve' }, buildId: '42' }) } })); const result = await doctor(root); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /path escapes|transient|sourceLocale/); });
test('migration plan is read-only and apply preserves a V1 backup', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await writeFile(path.join(root, '.git/info/exclude'), '/.ios-release/\nother\n'); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify({ schemaVersion: 1, defaultApp: 'app', apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', ascProfile: 'team', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); const plan = await migrate(root, 'plan'); assert.equal(plan.state, 'planned'); assert.equal(plan.portable.apps.app.releaseNotes.archiveDirectory, 'release-notes'); assert.equal((await stat(path.join(root, '.ios-release/context.json'))).isFile(), true); const applied = await migrate(root, 'apply'); assert.equal(applied.state, 'migrated'); const portable = JSON.parse(await readFile(path.join(root, '.ios-release/config.json'), 'utf8')); const local = JSON.parse(await readFile(path.join(root, '.ios-release/local.json'), 'utf8')); assert.equal(portable.apps.app.ascProfile, undefined); assert.equal(local.apps.app.ascProfile, 'team'); assert.equal((await stat(path.join(root, '.ios-release/context.v1.backup.json'))).isFile(), true); assert.doesNotMatch(await readFile(path.join(root, '.git/info/exclude'), 'utf8'), /\/\.ios-release\//); const rerun = await migrate(root, 'apply'); assert.equal(rerun.state, 'migrated'); assert.equal(rerun.sourcePresent, false); });
test('migration rejects a symlinked configuration directory before external writes', async () => { const root = await repo(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-migration-outside-')); roots.push(outside); await writeFile(path.join(outside, 'context.json'), JSON.stringify({ schemaVersion: 1, defaultApp: 'app', apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', ascProfile: 'team', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); await symlink(outside, path.join(root, '.ios-release')); await assert.rejects(migrate(root, 'apply'), /symlinks are forbidden/); assert.equal((await stat(path.join(outside, 'context.json'))).isFile(), true); await assert.rejects(readFile(path.join(outside, 'config.json')), /ENOENT/); await assert.rejects(readFile(path.join(outside, 'local.json')), /ENOENT/); });
test('migration stops for an archive-location choice', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await mkdir(path.join(root, 'release-notes/ios/app'), { recursive: true }); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify({ schemaVersion: 1, apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); const result = await migrate(root, 'plan'); assert.equal(result.state, 'incomplete'); assert.deepEqual(result.candidates.app, ['release-notes/ios/app', 'release-notes']); });
test('migration rejects an ignored archive candidate and fallback', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await mkdir(path.join(root, 'release-notes')); await writeFile(path.join(root, '.gitignore'), 'release-notes/\n'); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify({ schemaVersion: 1, apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', ascProfile: 'team', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } })); const result = await migrate(root, 'plan'); assert.notEqual(result.state, 'planned'); assert.match(result.errors.join('\n'), /ignored/); });
test('migration rejects malformed V1 root fields before transforming them', async () => { for (const old of [{ schemaVersion: 1, apps: [] }, { schemaVersion: 1, defaultApp: '', apps: {} }]) { const root = await repo(); await mkdir(path.join(root, '.ios-release')); await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify(old)); const result = await migrate(root, 'plan'); assert.equal(result.state, 'conflict'); assert.match(result.errors.join('\n'), /apps: expected an object|defaultApp: unknown app/); } });
test('migration reconciles equivalent existing JSON regardless of object key order', async () => { const root = await repo(); await mkdir(path.join(root, '.ios-release')); const old = { schemaVersion: 1, defaultApp: 'app', apps: { app: { bundleId: 'com.example.app', appId: '123456789', platform: 'IOS', ascProfile: 'team', xcode: { project: 'App.xcodeproj', scheme: 'App', configuration: 'Release' } } } }; await writeFile(path.join(root, '.ios-release/context.json'), JSON.stringify(old)); const plan = await migrate(root, 'plan'); assert.equal(plan.state, 'planned'); await writeFile(path.join(root, '.ios-release/.gitignore'), '*\n!.gitignore\n!config.json\n'); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ apps: plan.portable.apps, defaultApp: plan.portable.defaultApp, schemaVersion: plan.portable.schemaVersion })); await writeFile(path.join(root, '.ios-release/local.json'), JSON.stringify({ apps: plan.local.apps, schemaVersion: plan.local.schemaVersion })); assert.equal((await migrate(root, 'apply')).state, 'migrated'); });

test('portable schemas accept canonical paths, locales, and group IDs', async () => { const schema = JSON.parse(await readFile(new URL('../references/configuration.schema.json', import.meta.url), 'utf8')); const pathPattern = new RegExp(schema.$defs.path.pattern); const localePattern = new RegExp(schema.$defs.locale.pattern); const groupPattern = new RegExp(schema.$defs.group.properties.id.pattern); assert.equal(pathPattern.test('release-notes/archive'), true); assert.equal(pathPattern.test('release\rnotes'), false); assert.equal(pathPattern.test('release\nnotes'), false); assert.equal(localePattern.test('ja'), true); assert.equal(localePattern.test('zh-Hant'), true); assert.equal(groupPattern.test('12345678-1234-1234-1234-123456789abc'), true); assert.equal(groupPattern.test(`12345678${'-'.repeat(27)}`), false); });

test('CLI emits structured JSON', async () => { const root = await repo(); const result = spawnSync(process.execPath, [script, 'doctor', '--repo', root], { encoding: 'utf8' }); assert.equal(result.status, 1); assert.equal(JSON.parse(result.stdout).state, 'conflict'); });
