import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, symlink, unlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { checkReleaseNote, parseReleaseNote, renderReleaseNote } from './release-notes.mjs';

const roots = [];
async function fixture(promotionalText = 'preserve') { const root = await mkdtemp(path.join(os.tmpdir(), 'ios-release-notes-')); roots.push(root); execFileSync('git', ['init', '--quiet', root]); execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); await writeFile(path.join(root, 'source.txt'), 'baseline\n'); execFileSync('git', ['-C', root, 'add', 'source.txt']); execFileSync('git', ['-C', root, 'commit', '--quiet', '-m', 'baseline']); execFileSync('git', ['-C', root, 'tag', 'v2.3.0']); await writeFile(path.join(root, 'source.txt'), 'release\n'); execFileSync('git', ['-C', root, 'commit', '--quiet', '-am', 'release']); const commit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); await mkdir(path.join(root, '.ios-release'), { recursive: true }); await mkdir(path.join(root, 'release-notes'), { recursive: true }); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText } } } })); return { root, commit }; }
function note(commit, overrides = {}) { return renderReleaseNote({ app: 'app', marketingVersion: '2.4.0', sourceCommit: commit, sourceRange: `v2.3.0..${commit}`, locales: ['en-US', 'zh-Hant'], appStore: { 'en-US': 'Find saved items faster.', 'zh-Hant': '更快找到已儲存的項目。' }, ...overrides }); }
test.after(async () => { for (const root of roots) execFileSync('rm', ['-rf', root]); });
test('validates a complete archive and parses Unicode sections', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit)); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'valid'); assert.equal(result.parsed.appStore['zh-Hant'], '更快找到已儲存的項目。'); });
test('preserves archived source identity when checking its committed release state', async () => { const { root, commit } = await fixture(); const archive = path.join(root, 'release-notes/2.4.0.md'); await writeFile(archive, note(commit)); execFileSync('git', ['-C', root, 'add', 'release-notes/2.4.0.md']); execFileSync('git', ['-C', root, 'commit', '--quiet', '-m', 'release state']); const releaseCommit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: releaseCommit }).status, 'valid'); await writeFile(archive, note(commit).replace('Find saved items faster.', 'Uncommitted replacement.')); const changed = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: releaseCommit }); assert.equal(changed.status, 'conflict'); assert.match(changed.errors.join('\n'), /release-note-not-in-release-commit/); });
test('matches a committed release note through Git clean filters', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, '.gitattributes'), 'release-notes/*.md text eol=crlf\n'); execFileSync('git', ['-C', root, 'add', '.gitattributes']); execFileSync('git', ['-C', root, 'commit', '--quiet', '-m', 'configure release-note filter']); const sourceCommit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); const archive = path.join(root, 'release-notes/2.4.0.md'); await writeFile(archive, note(sourceCommit, { sourceRange: `${commit}..${sourceCommit}` })); execFileSync('git', ['-C', root, 'add', 'release-notes/2.4.0.md']); execFileSync('git', ['-C', root, 'commit', '--quiet', '-m', 'release state']); const releaseCommit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); await unlink(archive); execFileSync('git', ['-C', root, 'checkout', '--', 'release-notes/2.4.0.md']); execFileSync('git', ['-C', root, 'diff', '--quiet', '--', 'release-notes/2.4.0.md']); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: releaseCommit }).status, 'valid'); const changed = (await readFile(archive, 'utf8')).replace('Find saved items faster.', 'Uncommitted replacement.'); await writeFile(archive, changed); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: releaseCommit }).errors.join('\n'), /release-note-not-in-release-commit/); });
test('reports missing and conflicting archives', async () => { const { root, commit } = await fixture(); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'missing'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { appStore: { 'en-US': 'Only one locale.' } })); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /missing-locale/); });
test('rejects transient front matter, duplicate locales, and over-limit copy', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('"locales": [\n    "en-US",\n    "zh-Hant"\n  ]', '"locales": ["en-US", "en-US"],\n  "build": "99"').replace('Find saved items faster.', 'x'.repeat(4001)); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /transient|duplicate-locale|over-limit/); });
test('accepts complete optional promotional text under suggest and enforces its limit', async () => { const { root, commit } = await fixture('suggest'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'valid'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'x'.repeat(171), 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-over-limit/); });
test('rejects promotional text when policy is preserve', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-forbidden-by-policy/); });
test('rejects unexpected App Store locales', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('## Evidence', '### fr-FR\n\nNouveau.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /app-store-section-locale-mismatch/); });
test('rejects a release-note file symlink outside the repository', async () => { const { root, commit } = await fixture(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-note-outside-')); roots.push(outside); const outsideNote = path.join(outside, '2.4.0.md'); await writeFile(outsideNote, note(commit)); await symlink(outsideNote, path.join(root, 'release-notes/2.4.0.md')); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /archive-outside-repository|symlink/); });
test('rejects external and symlinked release configuration files', async () => { const { root, commit } = await fixture(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-config-gate-outside-')); roots.push(outside); const externalConfig = path.join(outside, 'config.json'); await writeFile(externalConfig, JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' } } } })); const external = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit, config: externalConfig }); assert.match(external.errors.join('\n'), /invalid-config.*escapes the repository/); await unlink(path.join(root, '.ios-release/config.json')); await symlink(externalConfig, path.join(root, '.ios-release/config.json')); const linked = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.match(linked.errors.join('\n'), /invalid-config.*symlinked/); });
test('rejects symlinked release configuration ancestors', async () => { const { root, commit } = await fixture(); const mutable = path.join(root, 'mutable-policy'); await mkdir(mutable); await writeFile(path.join(mutable, 'config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' } } } })); await unlink(path.join(root, '.ios-release/config.json')); await execFileSync('rmdir', [path.join(root, '.ios-release')]); await symlink(mutable, path.join(root, '.ios-release')); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.match(result.errors.join('\n'), /invalid-config.*symlinked component/); });
test('rejects release configuration stored in Git metadata', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, '.git/release-config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' } } } })); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit, config: '.git/release-config.json' }); assert.match(result.errors.join('\n'), /invalid-config.*Git metadata/); });
test('rejects release configuration stored in a nested repository', async () => { const { root, commit } = await fixture(); await mkdir(path.join(root, 'embedded')); execFileSync('git', ['init', '--quiet', path.join(root, 'embedded')]); await writeFile(path.join(root, 'embedded/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText: 'preserve' } } } })); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit, config: 'embedded/config.json' }); assert.match(result.errors.join('\n'), /invalid-config.*another Git repository/); });
test('requires source commits and ranges to resolve as Git commits', async () => { const { root, commit } = await fixture(); const blob = execFileSync('git', ['-C', root, 'hash-object', '-w', '--stdin'], { input: 'blob', encoding: 'utf8' }).trim(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(blob, { sourceRange: `v2.3.0..${blob}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: blob }).errors.join('\n'), /source-commit/); const missing = 'f'.repeat(40); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(missing, { sourceRange: `v2.3.0..${missing}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: missing }).errors.join('\n'), /source-commit-unresolved/); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { sourceRange: `missing-baseline..${commit}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /source-range/); });
test('requires the source range base to be a distinct ancestor', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { sourceRange: `${commit}..${commit}` })); const same = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(same.status, 'conflict'); assert.match(same.errors.join('\n'), /source-range-base-not-distinct/); const tree = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD^{tree}'], { encoding: 'utf8' }).trim(); const unrelated = execFileSync('git', ['-C', root, 'commit-tree', tree, '-m', 'unrelated'], { encoding: 'utf8' }).trim(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { sourceRange: `${unrelated}..${commit}` })); const nonAncestor = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(nonAncestor.status, 'conflict'); assert.match(nonAncestor.errors.join('\n'), /source-range-base-not-ancestor/); });
test('keeps version-derived note paths inside the archive directory', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'outside.md'), note(commit, { marketingVersion: '../outside' })); const result = checkReleaseNote({ repo: root, app: 'app', version: '../outside', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /invalid-marketing-version|archive-outside/); });
test('rejects malformed configured locale policies before reading copy', async () => { const { root, commit } = await fixture(); for (const locales of [[], 'en-US', ['bad'], ['en-US', 'en-US']]) { const configValue = JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales, promotionalText: 'preserve' } } } }); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit, configValue }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /invalid-locale-policy/); } });
test('parse reports malformed JSON front matter', () => { const parsed = parseReleaseNote('---\nnot json\n---\n\n## App Store What\'s New\n'); assert.match(parsed.errors.join('\n'), /valid JSON/); });
test('parse rejects non-object front matter and duplicate normalized sections', () => { for (const value of ['[]', 'null']) assert.match(parseReleaseNote(`---\n${value}\n---\n\n## App Store What's New\n\n## Evidence\n`).errors.join('\n'), /JSON object/); const duplicate = parseReleaseNote(`---\n{}\n---\n\n## App Store What's New\n\n## App Store What's New\n\n## Evidence\n`); assert.match(duplicate.errors.join('\n'), /duplicate section/); });
test('parse rejects unsupported top-level sections and empty evidence', () => { const unsupported = parseReleaseNote(`---\n{}\n---\n\n## App Store What's New\n\n## App Store Whats New\n\n## Evidence\n\nUsed: source\n`); assert.match(unsupported.errors.join('\n'), /unsupported top-level section/); const empty = parseReleaseNote(`---\n{}\n---\n\n## App Store What's New\n\n## Evidence\n`); assert.match(empty.errors.join('\n'), /Evidence section must not be empty/); });
test('parse rejects unscoped localized copy and permits leading whitespace', () => { const frontmatter = '---\n{"schemaVersion":1,"locales":["en-US"]}\n---\n\n'; const appStore = "## App Store What's New\n\n### en-US\n\nReady.\n\n"; const evidence = '## Evidence\n\nUsed: source\n'; for (const [title, label] of [["App Store What's New", "App Store What's New"], ['TestFlight What to Test', 'TestFlight What to Test'], ['Promotional Text', 'Promotional Text']]) { const localized = `## ${title}\n\nUnscoped copy.\n\n### en-US\n\nScoped copy.\n\n`; const markdown = `${frontmatter}${title === "App Store What's New" ? localized : `${appStore}${localized}`}${evidence}`; assert.match(parseReleaseNote(markdown).errors.join('\n'), new RegExp(`${label}: content before first locale heading`)); } const whitespace = `${frontmatter}## App Store What's New\n\n \t \n### en-US\n\nReady.\n\n${evidence}`; assert.doesNotMatch(parseReleaseNote(whitespace).errors.join('\n'), /content before first locale heading/); });
test('validates optional TestFlight locale coverage', async () => { const { root, commit } = await fixture(); const archive = note(commit, { testflight: { 'en-US': 'Try it.' } }).replace('## Evidence', '### fr-FR\n\nEssayez.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), archive); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /testflight-section-locale-mismatch/); const empty = note(commit).replace('## Evidence', '## TestFlight What to Test\n\nRaw text.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), empty); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /testflight-section-locale-mismatch/); });
test('rejects any promotional section under preserve policy', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('## Evidence', '## Promotional Text\n\nRaw text.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-forbidden-by-policy/); });
test('requires localized promotional copy when a suggest section is present', async () => { const { root, commit } = await fixture('suggest'); const markdown = note(commit).replace('## Evidence', '## Promotional Text\n\nRaw text.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-locale-mismatch/); });
