import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { checkReleaseNote, parseReleaseNote, renderReleaseNote } from './release-notes.mjs';

const roots = [];
async function fixture(promotionalText = 'preserve') { const root = await mkdtemp(path.join(os.tmpdir(), 'ios-release-notes-')); roots.push(root); execFileSync('git', ['init', '--quiet', root]); execFileSync('git', ['-C', root, 'config', 'user.name', 'Test']); execFileSync('git', ['-C', root, 'config', 'user.email', 'test@example.com']); await writeFile(path.join(root, 'source.txt'), 'baseline\n'); execFileSync('git', ['-C', root, 'add', 'source.txt']); execFileSync('git', ['-C', root, 'commit', '--quiet', '-m', 'baseline']); execFileSync('git', ['-C', root, 'tag', 'v2.3.0']); await writeFile(path.join(root, 'source.txt'), 'release\n'); execFileSync('git', ['-C', root, 'commit', '--quiet', '-am', 'release']); const commit = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(); await mkdir(path.join(root, '.ios-release'), { recursive: true }); await mkdir(path.join(root, 'release-notes'), { recursive: true }); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText } } } })); return { root, commit }; }
function note(commit, overrides = {}) { return renderReleaseNote({ app: 'app', marketingVersion: '2.4.0', sourceCommit: commit, sourceRange: `v2.3.0..${commit}`, locales: ['en-US', 'zh-Hant'], appStore: { 'en-US': 'Find saved items faster.', 'zh-Hant': '更快找到已儲存的項目。' }, ...overrides }); }
test.after(async () => { for (const root of roots) execFileSync('rm', ['-rf', root]); });
test('validates a complete archive and parses Unicode sections', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit)); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'valid'); assert.equal(result.parsed.appStore['zh-Hant'], '更快找到已儲存的項目。'); });
test('reports missing and conflicting archives', async () => { const { root, commit } = await fixture(); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'missing'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { appStore: { 'en-US': 'Only one locale.' } })); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /missing-locale/); });
test('rejects transient front matter, duplicate locales, and over-limit copy', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('"locales": [\n    "en-US",\n    "zh-Hant"\n  ]', '"locales": ["en-US", "en-US"],\n  "build": "99"').replace('Find saved items faster.', 'x'.repeat(4001)); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /transient|duplicate-locale|over-limit/); });
test('accepts complete optional promotional text under suggest and enforces its limit', async () => { const { root, commit } = await fixture('suggest'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'valid'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'x'.repeat(171), 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-over-limit/); });
test('rejects promotional text when policy is preserve', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-forbidden-by-policy/); });
test('rejects unexpected App Store locales', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('## Evidence', '### fr-FR\n\nNouveau.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /app-store-section-locale-mismatch/); });
test('rejects a release-note file symlink outside the repository', async () => { const { root, commit } = await fixture(); const outside = await mkdtemp(path.join(os.tmpdir(), 'ios-release-note-outside-')); roots.push(outside); const outsideNote = path.join(outside, '2.4.0.md'); await writeFile(outsideNote, note(commit)); await symlink(outsideNote, path.join(root, 'release-notes/2.4.0.md')); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /archive-outside-repository|symlink/); });
test('requires source commits and ranges to resolve as Git commits', async () => { const { root, commit } = await fixture(); const blob = execFileSync('git', ['-C', root, 'hash-object', '-w', '--stdin'], { input: 'blob', encoding: 'utf8' }).trim(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(blob, { sourceRange: `v2.3.0..${blob}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: blob }).errors.join('\n'), /source-commit/); const missing = 'f'.repeat(40); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(missing, { sourceRange: `v2.3.0..${missing}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: missing }).errors.join('\n'), /source-commit-unresolved/); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { sourceRange: `missing-baseline..${commit}` })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /source-range/); });
test('rejects malformed configured locale policies before reading copy', async () => { const { root, commit } = await fixture(); for (const locales of [[], 'en-US', ['bad'], ['en-US', 'en-US']]) { const configValue = JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales, promotionalText: 'preserve' } } } }); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit, configValue }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /invalid-locale-policy/); } });
test('parse reports malformed JSON front matter', () => { const parsed = parseReleaseNote('---\nnot json\n---\n\n## App Store What\'s New\n'); assert.match(parsed.errors.join('\n'), /valid JSON/); });
