import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { checkReleaseNote, parseReleaseNote, renderReleaseNote } from './release-notes.mjs';

const roots = [];
async function fixture(promotionalText = 'preserve') { const root = await mkdtemp(path.join(os.tmpdir(), 'ios-release-notes-')); roots.push(root); execFileSync('git', ['init', '--quiet', root]); await mkdir(path.join(root, '.ios-release'), { recursive: true }); await mkdir(path.join(root, 'release-notes'), { recursive: true }); const commit = execFileSync('git', ['-C', root, 'hash-object', '--stdin'], { input: 'source', encoding: 'utf8' }).trim().padEnd(40, '0').slice(0, 40); await writeFile(path.join(root, '.ios-release/config.json'), JSON.stringify({ schemaVersion: 2, apps: { app: { releaseNotes: { archiveDirectory: 'release-notes', sourceLocale: 'en-US', locales: ['en-US', 'zh-Hant'], promotionalText } } } })); return { root, commit }; }
function note(commit, overrides = {}) { return renderReleaseNote({ app: 'app', marketingVersion: '2.4.0', sourceCommit: commit, sourceRange: `v2.3.0..${commit}`, locales: ['en-US', 'zh-Hant'], appStore: { 'en-US': 'Find saved items faster.', 'zh-Hant': '更快找到已儲存的項目。' }, ...overrides }); }
test.after(async () => { for (const root of roots) execFileSync('rm', ['-rf', root]); });
test('validates a complete archive and parses Unicode sections', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit)); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'valid'); assert.equal(result.parsed.appStore['zh-Hant'], '更快找到已儲存的項目。'); });
test('reports missing and conflicting archives', async () => { const { root, commit } = await fixture(); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'missing'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { appStore: { 'en-US': 'Only one locale.' } })); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /missing-locale/); });
test('rejects transient front matter, duplicate locales, and over-limit copy', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('"locales": [\n    "en-US",\n    "zh-Hant"\n  ]', '"locales": ["en-US", "en-US"],\n  "build": "99"').replace('Find saved items faster.', 'x'.repeat(4001)); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); const result = checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }); assert.equal(result.status, 'conflict'); assert.match(result.errors.join('\n'), /transient|duplicate-locale|over-limit/); });
test('accepts complete optional promotional text under suggest and enforces its limit', async () => { const { root, commit } = await fixture('suggest'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.equal(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).status, 'valid'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'x'.repeat(171), 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-over-limit/); });
test('rejects promotional text when policy is preserve', async () => { const { root, commit } = await fixture(); await writeFile(path.join(root, 'release-notes/2.4.0.md'), note(commit, { promotionalText: { 'en-US': 'Discover faster search.', 'zh-Hant': '探索更快速的搜尋。' } })); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /promotional-text-forbidden-by-policy/); });
test('rejects unexpected App Store locales', async () => { const { root, commit } = await fixture(); const markdown = note(commit).replace('## Evidence', '### fr-FR\n\nNouveau.\n\n## Evidence'); await writeFile(path.join(root, 'release-notes/2.4.0.md'), markdown); assert.match(checkReleaseNote({ repo: root, app: 'app', version: '2.4.0', sourceCommit: commit }).errors.join('\n'), /app-store-section-locale-mismatch/); });
test('parse reports malformed JSON front matter', () => { const parsed = parseReleaseNote('---\nnot json\n---\n\n## App Store What\'s New\n'); assert.match(parsed.errors.join('\n'), /valid JSON/); });
